server:
    port: 8081

spring:
    boot:
        admin:
            client:
                url: http://${ADMIN_SERVER_HOST:admin-server}:${ADMIN_SERVER_PORT:9090}

    application:
        name: webhook-subscriber-dummy


management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        info:
            enabled: true
        prometheus:
            enabled: true 
        health:
            enabled: true
            show-details: "always"

logging:
    level.be.acerta: DEBUG
