# start up tasks ...
tasks:
- init: ./mvnw package -Djib.to.auth.username=$JIB_USER -Djib.to.auth.password=$JIB_PASSWORD -DskipTests -f ./wh-dispatcher/pom.xml
  command: java -jar ./wh-dispatcher/target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview