image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: redis-server
  - init: mvn package -Djib.to.auth.username=$JIB_USER -Djib.to.auth.password=$JIB_PASSWORD -DskipTests -f ./wh-admin-server/pom.xml
    command: mvn spring-boot:run -jar -f ./wh-admin-server/pom.xml
  - init: gp await-port 6379 && ./mvnw package -Djib.to.auth.username=$JIB_USER -Djib.to.auth.password=$JIB_PASSWORD -DskipTests -f ./wh-dispatcher/pom.xml && java -jar ./wh-dispatcher/target/*.jar
    command: gp await-port 8080 && gp preview $(gp url 8080)/browser/browser.html

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: ignore
  - port: 6379
    onOpen: ignore

vscode:
  extensions:
    - mathiasfrohlich.kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    - scala-lang.scala@0.5.0:3FIiaU1vnooQsX3PkBlBvQ==
    - vscjava.vscode-spring-boot-dashboard@0.2.0:qjoUjsBMX4msxil1rg0vMA==
    - k--kato.intellij-idea-keybindings@1.3.0:L2TsjXwd374imGVuEPtE1g==
