image:
  file: .gitpod.Dockerfile

# See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: redis-server --daemonize yes && prometheus --config.file=./prometheus/prometheus.yml
  - command: mvn spring-boot:run -f ./wh-admin-server/pom.xml -ntp
  - command: gp await-port 6379 && gp await-port 8090 && gp await-port 8081 && ./clear-redis.sh && mvn spring-boot:run -f ./wh-dispatcher/pom.xml -ntp
  - command: mvn spring-boot:run -f ./wh-subscriber-dummy/pom.xml -ntp && gp await-port 8081 && exit
  - command: gp await-port 8080 && gp await-port 8081 && ./create-webhook.sh && exit

# See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: ignore
  - port: 8090
    onOpen: open-browser
  - port: 6379
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 9090
    onOpen: ignore

vscode:
  extensions:
    - mathiasfrohlich.kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    - scala-lang.scala@0.5.0:3FIiaU1vnooQsX3PkBlBvQ==
    - pivotal.vscode-spring-boot@1.24.0:OTueaV6r/33nqwmew2TbJg==
    - vscjava.vscode-spring-boot-dashboard@0.2.0:qjoUjsBMX4msxil1rg0vMA==
    - k--kato.intellij-idea-keybindings@1.3.0:L2TsjXwd374imGVuEPtE1g==
