# start up tasks
tasks:
- init: ./mvnw package -Djib.to.auth.username=cbonami -DskipTests -f ./wh-dispatcher/pom.xml
  command: java -jar ./wh-dispatcher/target/*.jar

# exposed ports
ports:
- port: 8080
  onOpen: open-preview