language: java
jdk:
    - openjdk11

services:
    - redis-server

before_install:
    - chmod +x mvnw

install: echo "My projects will be configurable in an awesomical way ;)."

script: ./mvnw spring-boot:build-image
