server:
    port: 8080


#JPA Configuration
spring:
    application:
        name: webhook-service
    profiles:
        active: local
logging.level.be.acerta: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: "*"
