server:
    port: 8080


#JPA Configuration
spring:
    application:
        name: webhook-dispatcher
    profiles:
        active: local
logging.level.be.acerta: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: "*"

redis:
    url: redis://localhost:6379
    password: bar