server:
    port: 8090

spring:
    application:
        name: webhook-admin-server
    profiles:
        active: local

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"

logging.level.be.acerta: DEBUG