server:
    port: 8081

spring:
    boot:
        admin:
            client:
                url: http://localhost:9090

    application:
        name: webhook-subscriber-fake


management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"

logging.level.be.acerta: DEBUG
