server:
    port: 8080

spring:
    boot:
        admin:
            client:
                url: http://${ADMIN_SERVER_HOST:admin-server}:${ADMIN_SERVER_PORT:9090}
    application:
        name: webhook-dispatcher
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"

redis:
    url: redis://localhost:6379
    password: bar
logging.level.be.acerta: DEBUG