server:
    port: 8080

spring:
    boot:
        admin:
            client:
                url: http://${ADMIN_SERVER_HOST:localhost}:${ADMIN_SERVER_PORT:8090}
    application:
        name: webhook-dispatcher
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"
    metrics:
        tags:
            application: ${spring.application.name}

redis:
    host: ${REDIS_SERVER_HOST:localhost}
    port: 6379
    password: bar

logging:
    file:
        name: target/app.log
    level:
        be.acerta: DEBUG
        #org.springframework.boot.autoconfigure.logging: DEBUG