// create a new destination (=application)
POST http://localhost:8080/applications
Content-Type: application/json

{"url":"http://ptsv2.com/post.php?dir=webok","name":"foo app"}
###

// list all applications
GET http://localhost:8080/applications
###

POST http://localhost:8080/applications/948ec2d7-6e66-4e05-9a4c-c0768346106a/message
Content-type: text/plain

WEBHOOK-TEST
