// create a new destination (=application)
POST http://localhost:8080/applications HTTP/1.1
Content-Type: application/x-www-form-urlencoded

url=http%3A%2F%2Fptsv2.com%2Fpost.php%3Fdir%3Dwebok&name=test2%20app
###

// list all applications
GET http://localhost:8080/applications
###

POST http://localhost:8080/applications/948ec2d7-6e66-4e05-9a4c-c0768346106a/message
Content-type: text/plain

WEBHOOK-TEST
